#!/usr/bin/env bash
# Render env-templated configs, ensure EFS dirs, then hand off to supervisord.
set -euo pipefail

log() { echo "[forge-entrypoint] $*"; }

# MinIO root creds are injected from Secrets Manager (forge/minio/root) as the
# MINIO_ROOT_USER / MINIO_ROOT_PASSWORD env vars by the ECS task definition.
# If the secret is a JSON blob ({"username":...,"password":...}) the task def
# maps the individual keys; we only consume the resolved env vars here.
: "${NGINX_WORKERS:=auto}"
: "${FORGEJO_HTTP_PORT:=3000}"
: "${SYSML_API_PORT:=9000}"
: "${SYSML_JAVA_PORT:=8003}"
: "${MINIO_API_PORT:=9090}"
: "${MINIO_CONSOLE_PORT:=9091}"
: "${FORGEJO_DOMAIN:=git.forge.local}"
: "${FORGEJO_ROOT_URL:=http://${FORGEJO_DOMAIN}/}"
export NGINX_WORKERS FORGEJO_HTTP_PORT SYSML_API_PORT SYSML_JAVA_PORT \
       MINIO_API_PORT MINIO_CONSOLE_PORT FORGEJO_DOMAIN FORGEJO_ROOT_URL

# ── EFS-backed data roots ────────────────────────────────────
mkdir -p /forge/repos /forge/minio
chown -R git:git /forge/repos || true

# ── Render nginx.conf ────────────────────────────────────────
envsubst '${NGINX_WORKERS} ${FORGEJO_HTTP_PORT} ${SYSML_API_PORT} ${MINIO_API_PORT} ${FORGEJO_DOMAIN}' \
    < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf.rendered
mv /etc/nginx/nginx.conf.rendered /etc/nginx/nginx.conf
nginx -t

# ── Render Forgejo app.ini (only if not already present on EFS) ──
# We keep app.ini on the ephemeral container FS; repos/db live on EFS so the
# install survives. SECRET_KEY/INTERNAL_TOKEN are derived deterministically
# from the Forgejo PAT secret when supplied, else auto-generated by Forgejo.
mkdir -p /etc/forgejo
envsubst '${FORGEJO_HTTP_PORT} ${FORGEJO_DOMAIN} ${FORGEJO_ROOT_URL}' \
    < /etc/forgejo/app.ini.tmpl > /etc/forgejo/app.ini
chown git:git /etc/forgejo/app.ini

log "config rendered: forgejo=${FORGEJO_DOMAIN}:${FORGEJO_HTTP_PORT} sysml-api=:${SYSML_API_PORT} (java :${SYSML_JAVA_PORT}) minio=:${MINIO_API_PORT}"

exec "$@"
